/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const JournalId = IDL.Nat;
export const ItemId = IDL.Nat;
export const Timestamp = IDL.Int;
export const BucketListItem = IDL.Record({
  'id' : ItemId,
  'title' : IDL.Text,
  'created' : Timestamp,
  'note' : IDL.Text,
  'completed' : IDL.Bool,
  'journalId' : JournalId,
  'vaulted' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MemberRole = IDL.Variant({
  'member' : IDL.Null,
  'owner' : IDL.Null,
});
export const Member = IDL.Record({
  'principal' : IDL.Principal,
  'joinedAt' : Timestamp,
  'role' : MemberRole,
});
export const Journal = IDL.Record({
  'id' : JournalId,
  'title' : IDL.Text,
  'created' : Timestamp,
  'members' : IDL.Vec(Member),
  'owner' : IDL.Principal,
  'description' : IDL.Text,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const InvitationLink = IDL.Record({
  'created' : Timestamp,
  'code' : IDL.Text,
  'journalId' : JournalId,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addBucketListItem' : IDL.Func(
      [JournalId, IDL.Text, IDL.Text],
      [BucketListItem],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createJournal' : IDL.Func([IDL.Text, IDL.Text], [Journal], []),
  'deleteBucketListItem' : IDL.Func([ItemId], [IDL.Bool], []),
  'editBucketListItem' : IDL.Func(
      [ItemId, IDL.Text, IDL.Text],
      [IDL.Opt(BucketListItem)],
      [],
    ),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'generateInvitationLink' : IDL.Func([JournalId], [InvitationLink], []),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJournal' : IDL.Func([JournalId], [IDL.Opt(Journal)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinJournal' : IDL.Func([IDL.Text], [Journal], []),
  'listBucketListItems' : IDL.Func(
      [JournalId],
      [IDL.Vec(BucketListItem)],
      ['query'],
    ),
  'listMembers' : IDL.Func([JournalId], [IDL.Vec(Member)], ['query']),
  'listMyJournals' : IDL.Func([], [IDL.Vec(Journal)], ['query']),
  'removeMember' : IDL.Func([JournalId, IDL.Principal], [Journal], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'setBucketListItemCompleted' : IDL.Func(
      [ItemId, IDL.Bool],
      [IDL.Opt(BucketListItem)],
      [],
    ),
  'setBucketListItemVaulted' : IDL.Func(
      [ItemId, IDL.Bool],
      [IDL.Opt(BucketListItem)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const JournalId = IDL.Nat;
  const ItemId = IDL.Nat;
  const Timestamp = IDL.Int;
  const BucketListItem = IDL.Record({
    'id' : ItemId,
    'title' : IDL.Text,
    'created' : Timestamp,
    'note' : IDL.Text,
    'completed' : IDL.Bool,
    'journalId' : JournalId,
    'vaulted' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MemberRole = IDL.Variant({ 'member' : IDL.Null, 'owner' : IDL.Null });
  const Member = IDL.Record({
    'principal' : IDL.Principal,
    'joinedAt' : Timestamp,
    'role' : MemberRole,
  });
  const Journal = IDL.Record({
    'id' : JournalId,
    'title' : IDL.Text,
    'created' : Timestamp,
    'members' : IDL.Vec(Member),
    'owner' : IDL.Principal,
    'description' : IDL.Text,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const InvitationLink = IDL.Record({
    'created' : Timestamp,
    'code' : IDL.Text,
    'journalId' : JournalId,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addBucketListItem' : IDL.Func(
        [JournalId, IDL.Text, IDL.Text],
        [BucketListItem],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createJournal' : IDL.Func([IDL.Text, IDL.Text], [Journal], []),
    'deleteBucketListItem' : IDL.Func([ItemId], [IDL.Bool], []),
    'editBucketListItem' : IDL.Func(
        [ItemId, IDL.Text, IDL.Text],
        [IDL.Opt(BucketListItem)],
        [],
      ),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'generateInvitationLink' : IDL.Func([JournalId], [InvitationLink], []),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJournal' : IDL.Func([JournalId], [IDL.Opt(Journal)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinJournal' : IDL.Func([IDL.Text], [Journal], []),
    'listBucketListItems' : IDL.Func(
        [JournalId],
        [IDL.Vec(BucketListItem)],
        ['query'],
      ),
    'listMembers' : IDL.Func([JournalId], [IDL.Vec(Member)], ['query']),
    'listMyJournals' : IDL.Func([], [IDL.Vec(Journal)], ['query']),
    'removeMember' : IDL.Func([JournalId, IDL.Principal], [Journal], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'setBucketListItemCompleted' : IDL.Func(
        [ItemId, IDL.Bool],
        [IDL.Opt(BucketListItem)],
        [],
      ),
    'setBucketListItemVaulted' : IDL.Func(
        [ItemId, IDL.Bool],
        [IDL.Opt(BucketListItem)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };