/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BucketListItem {
  'id' : ItemId,
  'title' : string,
  'created' : Timestamp,
  'note' : string,
  'completed' : boolean,
  'journalId' : JournalId,
  'vaulted' : boolean,
}
export interface Cell { 'value' : Value, 'name' : string }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface InvitationLink {
  'created' : Timestamp,
  'code' : string,
  'journalId' : JournalId,
}
export type ItemId = bigint;
export interface Journal {
  'id' : JournalId,
  'title' : string,
  'created' : Timestamp,
  'members' : Array<Member>,
  'owner' : Principal,
  'description' : string,
}
export type JournalId = bigint;
export interface Member {
  'principal' : Principal,
  'joinedAt' : Timestamp,
  'role' : MemberRole,
}
export type MemberRole = { 'member' : null } |
  { 'owner' : null };
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addBucketListItem' : ActorMethod<
    [JournalId, string, string],
    BucketListItem
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createJournal' : ActorMethod<[string, string], Journal>,
  'deleteBucketListItem' : ActorMethod<[ItemId], boolean>,
  'editBucketListItem' : ActorMethod<
    [ItemId, string, string],
    [] | [BucketListItem]
  >,
  'execute' : ActorMethod<[string], Result>,
  'generateInvitationLink' : ActorMethod<[JournalId], InvitationLink>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJournal' : ActorMethod<[JournalId], [] | [Journal]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinJournal' : ActorMethod<[string], Journal>,
  'listBucketListItems' : ActorMethod<[JournalId], Array<BucketListItem>>,
  'listMembers' : ActorMethod<[JournalId], Array<Member>>,
  'listMyJournals' : ActorMethod<[], Array<Journal>>,
  'removeMember' : ActorMethod<[JournalId, Principal], Journal>,
  'schema' : ActorMethod<[], string>,
  'setBucketListItemCompleted' : ActorMethod<
    [ItemId, boolean],
    [] | [BucketListItem]
  >,
  'setBucketListItemVaulted' : ActorMethod<
    [ItemId, boolean],
    [] | [BucketListItem]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];